[package]
name = "xbee_rust_modem_library"
version = "0.1.0"
edition = "2024"
default-run = "xbee_rust_modem_library"

[dependencies]
serialport = "4.8.1"

serde = { version = "1.0", features = ["derive"] }
postcard = { version = "1.1", features = ["use-std"] }
heapless = { version = "0.8", features = ["serde"] }

aes-gcm = { version = "0.10.3", features = ["heapless"] }
hkdf = "0.12"
sha2 = "0.10"

ed25519-dalek = { version = "2", features = ["rand_core"] }
x25519-dalek = { version = "2", features = ["getrandom"] }

rand_core = { version = "0.6", features = ["getrandom"] }

base64ct = { version = "1", features = ["std"] }
